version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
install:
- ps: |
    nuget install inheritdoc -Version 1.2.0.1
build_script:
- ps: |
    dotnet build -c Release
    & $env:USERPROFILE\.nuget\packages\inheritdoc\1.2.0.1\tools\InheritDoc.exe -o -b .\src\Prism\bin\Release
    dotnet pack --no-build -c Release /p:version=$env:APPVEYOR_REPO_TAG_NAME
test_script:
- ps: |
    cd .\test\Prism.Tests
    dotnet test -c Release -l trx -r ./ --no-build .\Jering.Web.SyntaxHighlighters.Prism.Tests.csproj
    if($LastExitCode -ne 0){
        throw "Tests failed."
    }
    # $wc = New-Object 'System.Net.WebClient'
    # $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\*.trx))
artifacts:
  - path: '.\src\Prism\bin\Release\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: YuSNfK09e6bNa8EEC2jAsTZP8b8sHN6BDdhrqbI1hRAoqSAUUre5gH8CaW/85NpF
  skip_symbols: false
  artifact: /.*\.nupkg/
cache:
    - '%USERPROFILE%\.nuget\packages -> **\*.csproj'