trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeringTech/DevOps.AzurePipelines
    endpoint: JeringTech

jobs:
- template: templates/nuget/main.yml@templates
  parameters:
    changelogPath: "Changelog.md"
    nugetUnreleasedPrereleasePushEndpoint: "https://www.myget.org/F/jering/api/v3/index.json"
- template: templates/docs/main.yml@templates
  parameters:
    nugetRestoreEndpoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/nuget/v2"
    nugetRestorePat: "$(nugetRestorePat)"